apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"grafana-pvc","namespace":"my-grafana"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}}}
  creationTimestamp: "2026-07-09T19:25:40Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: grafana-pvc
  namespace: my-grafana
  resourceVersion: ""
  uid: 32c9f767-187f-46bf-8ab4-e199ee3dfd52
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: "my-grafana-plugin"
status:
  phase: Pending
