apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"grafana","namespace":"my-grafana"},"spec":{"ports":[{"port":3000,"protocol":"TCP","targetPort":"http-grafana"}],"selector":{"app":"grafana"},"sessionAffinity":"None","type":"LoadBalancer"}}
    creationTimestamp: "2026-07-09T19:25:40Z"
    name: grafana
    namespace: my-grafana
    resourceVersion: "4102"
    uid: 6ddfe8f7-063c-4132-9283-a6a79957d0ef
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.111.98.134
    clusterIPs:
    - 10.111.98.134
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30722
      port: 3000
      protocol: TCP
      targetPort: http-grafana
    selector:
      app: grafana
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
